### ISSUE TITLE
panic at main.rs:133:66

### ISSUE THREAD

**Issue by gessel** [rsadsb/dump1090_rs#139]
I tried with both compiled and with downloaded binaries and got the same result:

```
./dump1090_rs 
[-] using soapysdr driver_args: driver=rtlsdr
Found Elonics E4000 tuner
[INFO] Opening Generic RTL2832U OEM :: 00000001...
Found Elonics E4000 tuner
[-] using config: Sdr {
    channel: 0,
    driver: "rtlsdr",
    setting: None,
    gain: [
        Gain {
            key: "TUNER",
            value: 49.6,
        },
    ],
    antenna: None,
}
[-] Writing gain: TUNER = 49.6
[E4K] PLL not locked for 1090000000 Hz!
thread 'main' panicked at dump1090_rs/src/main.rs:133:66:
called `Result::unwrap()` on an `Err` value: Error { code: Other, message: "setFrequency failed" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
The USB SDR is recognized as a RTL2832U by cubic, but cubic also barfs right around 1090, however sigdigger seems to have no trouble at that frequency:

![image](https://github.com/user-attachments/assets/f9d33f06-af6f-4fd7-93a8-570ee0fdfab0)

Any hints?

**Comment by gessel** [comment]
Thanks, it's the hardware, I shoulda run `rtl_test -t` first. I'm not sure why, now sigdigger wasn't having a problem, but hitting a band gap seems to cause a barf.  

```
rtl_test -t
Found 1 device(s):
  0:  Realtek, RTL2838UHIDIR, SN: 00000001

Using device 0: Generic RTL2832U OEM
Found Elonics E4000 tuner
Supported gain values (14): -1.0 1.5 4.0 6.5 9.0 11.5 14.0 16.5 19.0 21.5 24.0 29.0 34.0 42.0 
Sampling at 2048000 S/s.
Benchmarking E4000 PLL...
[E4K] PLL not locked for 51000000 Hz!
[E4K] PLL not locked for 2168000000 Hz!
[E4K] PLL not locked for 1085000000 Hz!
[E4K] PLL not locked for 1249000000 Hz!
E4K range: 52 to 2167 MHz
E4K L-band gap: 1085 to 1249 MHz
```

This is a known (TIL) limitation of this particular variant of the RTL-2832U: https://osmocom.org/projects/rtl-sdr/wiki/Rtl-sdr

I'ma close this as resolved as it is not a software issue.
